### ISSUE TITLE
Wondering if these named read macros can be shadowed  by local variables with the same name.

### ISSUE THREAD

**Issue by ghost** [williamyaoh/named-read-macros#1]
Typically with a classical macro these locals will be figured out at compile-time, and if one happens to be the head of s-expr, it will not get macro-expanded, but called as a function at runtime.

Discussion: https://www.reddit.com/r/lisp/comments/d6evj6/is_there_a_lisp_that_accepts_sexprs_as_reader/

**Comment by williamyaoh** [comment]
Short answer is no, the read macro will get used instead.

The relevant code is in `read-maybe-read-macro`, where we hijack the reader for #'( and check if the head symbol has an attached read macro; if it does, we expand, if not, we just leave it as is.
